routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//
Auth::routes();
//Auth::loginUsingId(1);
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', function(){
        return redirect('home');
    })->name('home');
    /*permissions*/
    Route::resource('permissions', 'PermissionController');
    Route::get('permissions-datatable', 'PermissionController@permissionDatatable')->name('permissions.datatable');

    /*roles*/
    Route::resource('roles', 'RoleController');
    Route::get('roles-datatable', 'RoleController@roleDatatable')->name('roles.datatable');

    /*users*/
    Route::resource('users', 'UserController');
    Route::DELETE('users-enabled/{user}', 'UserController@userEnabled')->name('users.enabled');
    Route::get('users-datatable', 'UserController@usersDatatable')->name('users.datatable');
//    Route::get('users-profile/{user}', 'UserController@usersDatatable')->name('users.profile');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends \Spatie\Permission\Models\Role
{
    protected $casts = [
        'created_at' => 'datetime:M d, Y h:i:s a',
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\Facades\DataTables;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        if (! Gate::allows('role_view')) {
//            return abort(403);
//        }
        return view('app.pages.roles.index');
    }

    public function roleDatatable(){
        if (! Gate::allows('role_view')) {
            return abort(403);
        }
        $data = \App\Role::query();
        return DataTables::of($data)
            ->addColumn('permissions',function ($data){
                $permissions = $data->permissions()->pluck('name');
                $html='';
                if(count($permissions)>0){
                    foreach($permissions as $permission) {
                        $html .= '<span class="badge badge-primary">' . $permission . '</span>';
                    }
                }else{
                    $html.='<p>No Permission</p>';
                }

                return $html;
            })
            ->addColumn('action', function ($data) {
                $html='<a href="" type="button" data-btn="edit" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg">
                        <span class="label label-info">Edit</span>
                        </a>';
                $html.='<a href="" type="button" data-btn="delete" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg-delete">
                        <span class="label label-danger">Delete</span>
                        </a>';
                return  $html;
            })
            ->rawColumns(['action','permissions'])
            ->toArray();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('role_create')) {
            return abort(403);
        }
        $permissions = Permission::all();
        //render form
        $form = view()->make('app.pages.roles._form',compact('permissions'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('role_create')) {
            return abort(403);
        }

        $request->validate([
            'name' => 'required|unique:roles,name|regex:/(^[A-Za-z0-9-_]+$)+/',
            'permissions'=>'required'
        ]);
        $role = Role::create($request->except('permissions'));
        $permissions = $request->input('permissions') ? $request->input('permissions') : [];
        $role->givePermissionTo($permissions);
        if($role){
            return  response()->json([
                'status'=>'success',
                'message'=>'Role Successfully Added'
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('role_update')) {
            return abort(403);
        }
        $permissions = Permission::all();
        $role = Role::findOrFail($id);
        $form = view()->make('app.pages.roles._form',compact('permissions','role'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('role_update')) {
            return abort(403);
        }
        $request->validate([
            'name' => 'required|unique:roles,name,'.$request->role.'|regex:/(^[A-Za-z0-9-_]+$)+/',
            'permissions'=>'required'
        ]);

        $role = Role::findOrFail($id);
        $role->update($request->except('permissions'));
        $permissions = $request->input('permissions') ? $request->input('permissions') : [];
        $role->syncPermissions($permissions);

        if($role){
            return  response()->json([
                'status'=>'success',
                'message'=>'Role Successfully Updated'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('role_delete')) {
            return abort(403);
        }
        $role = Role::findOrFail($id);
        $role->delete();

        if($role){
            return  response()->json([
                'status'=>'success',
                'message'=>'Role Successfully Deleted',
            ]);
        }
    }
}

resources/views/app/pages/roles/_form.blade.php
<form id="form" class="form-horizontal form-label-left">
    @csrf
    @isset($role)
        {{ method_field('PUT') }}
    @endisset
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Role Name <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="name" required="required" value="{{$role->name ?? ''}}" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-3 col-sm-3 col-xs-12 control-label">Select Permission
            <br>
            <small class="text-navy">Role can have 1 or more permissions</small>
        </label>
        <div class="col-md-9 col-sm-9 col-xs-12">

                @forelse($permissions as $key=>$permission)
                <div class="checkbox">
                    <label>
                        @if(isset($role))
                            <input type="checkbox" class="flat" name="permissions[]" value="{{$permission->name}}"
                                   @foreach($role->permissions()->pluck('name') as $roles)
                                           @if($roles== $permission->name)
                                           checked="checked"
                                        @endif
                                @endforeach
                            > {{$permission->name}}
                        @else
                            <input type="checkbox" class="flat" name="permissions[]" value="{{$permission->name}}" > {{$permission->name}}
                        @endif
                    </label>
                </div>
                @empty
                <div class="checkbox">
                    <label>
                       No Permissions
                    </label>
                </div>
                @endforelse
        </div>
    </div>
</form>

resources/views/app/pages/roles/_scripts.blade.php
<script>
    var btn;
    var modal;
    var form;
    $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#roles-datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,

            ajax:{
                "url": '{!! route("roles.datatable") !!}',
                "type": "GET",
            },
            columns: [
                { data: 'name', name: 'name' },
                { data: 'permissions', name: 'permissions' },
                { data: 'created_at', name: 'created_at'},
                { data: 'action', name: 'action',searchable:false,orderable:false},

            ],
            columnDefs:[
                {targets:3,"width":"10%"}
            ],
            "order": [[ 0, "asc" ]], //or asc
        });

    });

    /*render create-edit modal*/
    $('#modal-lg').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var button = $(event.relatedTarget); // Button that triggered the modal
        btn = button.data('btn'); // Extract info from data-* attributes
        modal = $(this);
        modal.find('.btn-modal-submit').css('display','');
        form = modal.find(".modal-body #form");
        form.trigger('reset');
        if (btn === 'create') {
            var url = '{{ route("roles.create")}}';
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    modal.find('.modal-title').html('CREATE ROLE');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    $('input.flat').iCheck({
                        checkboxClass: 'icheckbox_flat-green',
                        radioClass: 'iradio_flat-green'
                    });
                    form.attr('action', '{{ route("roles.store")}}');
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Save');
                }
            })//end ajax
        } else if (btn === 'edit') {
            var role_id = button.data('id');
            var url = '{{ route("roles.edit",":role_id")}}';
            url = url.replace(':role_id', role_id);
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    var url = '{{ route("roles.update",":role_id")}}';
                    url = url.replace(':role_id', role_id);
                    modal.find('.modal-title').html('EDIT ROLE');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    form.find('input.flat').iCheck({
                        checkboxClass: 'icheckbox_flat-green',
                        radioClass: 'iradio_flat-green'
                    });
                    form.attr('action', url);
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Update');
                }
            })//end ajax
        }
    });

    $('#modal-lg-delete').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var button = $(event.relatedTarget); // Button that triggered the modal
        var role_id = button.data('id');// Extract info from data-* attributes
        var url = '{{ route("roles.destroy", ":role_id") }}';
        modal.find('.btn-modal-submit').css('display','');
        btn = button.data('btn');
        url = url.replace(':role_id', role_id);
        modal = $(this);
        form = modal.find('.modal-body #form-delete');
        console.log(form);
        form.attr('action', url);
        console.log(form.attr('action', url));
        modal.find('.modal-title').html('DELETE ROLE');
        modal.find('.modal-body #message').html(' <strong>Role will be DELETED!</strong> Are you sure to process this transaction?');
    });

    /*AJAX SUBMIT*/
    $(".btn-modal-submit").click(function (e) {
        e.preventDefault(); // avoid to execute the actual submit of the form.
        var url =  form.attr('action');
        console.log(url);
        $.ajax({
            type: form.attr('method'),
            url: url,
            data: form.serialize(), // serializes the form's elements.
            success: function (data) {
                checkValidation(form,data);
                $('#roles-datatable').DataTable().ajax.reload();
                if(btn !== 'delete'){
                    modal.find('.modal-body #name').val(data.name)
                }
            }, error: function (xhr, ajaxOptions, thrownError) {
                checkValidation(form,xhr)
            }
        });
    });

    /*functions*/

    function checkValidation(form,data){
        if(data.status==='success'){
            var success = modal.find('.success-modal');
            success.fadeIn();
            success.html(data.message);
            success.css('display','');
            form.trigger("reset");
            if(btn==='create'){
                form.find('input.flat').iCheck('update');
            }

            if(btn==='delete'){
                modal.find('.btn-modal-submit').css('display','none');
            }
            success.delay(800).fadeOut(300, function(){
                success.css('display','none');
                if(btn==='delete'){
                    modal.modal('toggle');
                }
            });
        }else{
            var error = modal.find('.error-modal');
            var message = '';
            $.each(data.responseJSON.errors, function (key, value) {
                message += value
            });
            console.log(message);
            error.fadeIn();
            error.html(message);
            error.css('display','');
            error.delay(800).fadeOut(300, function(){
                error.css('display','none');
            })
        }
    }


</script>

resources/views/app/pages/roles/index.blade.php
@extends("app.layout.app")
@section("title","Roles")
@push("page-styles")
    <!-- bootstrap-progressbar -->
    <link href="{{asset("theme/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css")}}" rel="stylesheet">

    <!-- Datatables -->
    <link href="{{asset('theme')}}/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
@endpush

@section("content")
    <div style="margin-top: 50px;">
        <div class="page-title">
            <div class="title_left">
                <h3>Roles</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <button type="button" class="btn btn-success" data-btn="create" data-toggle="modal" data-target="#modal-lg"><i class="fa fa-plus"></i> Create Roles</button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">

                            <table id="roles-datatable" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Permissions</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push("page-scripts")
    <!-- iCheck -->
    <script src="{{asset('theme')}}/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="{{asset('theme')}}/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="{{asset('theme')}}/vendors/jszip/dist/jszip.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="{{asset('theme')}}/vendors/validator/validator.js"></script>
    <script src="{{asset('theme')}}/vendors/moment/moment.js"></script>
@endpush

@push("scripts")
    @include('app.pages.roles._scripts')
@endpush