routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//
Auth::routes();
//Auth::loginUsingId(1);
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', function(){
        return redirect('home');
    })->name('home');
    /*permissions*/
    Route::resource('permissions', 'PermissionController');
    Route::get('permissions-datatable', 'PermissionController@permissionDatatable')->name('permissions.datatable');

    /*roles*/
    Route::resource('roles', 'RoleController');
    Route::get('roles-datatable', 'RoleController@roleDatatable')->name('roles.datatable');

    /*users*/
    Route::resource('users', 'UserController');
    Route::DELETE('users-enabled/{user}', 'UserController@userEnabled')->name('users.enabled');
    Route::get('users-datatable', 'UserController@usersDatatable')->name('users.datatable');
//    Route::get('users-profile/{user}', 'UserController@usersDatatable')->name('users.profile');
});

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends \Spatie\Permission\Models\Permission
{
    protected $casts = [
        'created_at' => 'datetime:M d, Y h:i:s a',
    ];

}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Validator;
//use Spatie\Permission\Models\Permission;
use Yajra\DataTables\Facades\DataTables;
use App\Permission;


class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('permission_view')) {
            return abort(403);
        }
        return view('app.pages.permissions.index');
    }

    public function permissionDatatable(){
        if (! Gate::allows('permission_view')) {
            return abort(403);
        }
        $data = Permission::query();
        return DataTables::of($data)
            ->addColumn('action', function ($data) {
                $html='<a href="" type="button" data-btn="edit" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg">
                        <span class="label label-info">Edit</span>
                        </a>';
                $html.='<a href="" type="button" data-btn="delete" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg-delete">
                        <span class="label label-danger">Delete</span>
                        </a>';
                return  $html;
            })
            ->rawColumns(['action'])
            ->toArray();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('permission_create')) {
            return abort(403);
        }
        //render form
        $form = view()->make('app.pages.permissions._form')->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('permission_create')) {
            return abort(403);
        }
        $request->validate([
            'name' => 'required|unique:permissions,name|regex:/(^[A-Za-z0-9-_]+$)+/',
        ]);
        $permission = Permission::create($request->all());
        if($permission){
            return  response()->json([
                'status'=>'success',
                'message'=>'Permission Successfully Added'
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('permission_update')) {
            return abort(403);
        }
        $permission = Permission::find($id);
        $form = view()->make('app.pages.permissions._form',compact('permission'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('permission_update')) {
            return abort(403);
        }
        $request->validate([
            'name' => 'required|unique:permissions,name,'.$request->permission.'|regex:/(^[A-Za-z0-9-_]+$)+/',
        ]);
        $permission = Permission::find($id);
        $permission->name = $request->name;
        $permission->save();

        if($permission){
            return  response()->json([
                'status'=>'success',
                'message'=>'Permission Successfully Updated',
                'name'=>$request->name
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('permission_delete')) {
            return abort(403);
        }
        $permission = \Spatie\Permission\Models\Permission::findOrFail($id);
        $permission->delete();

        if($permission){
            return  response()->json([
                'status'=>'success',
                'message'=>'Permission Successfully Deleted',
            ]);
        }
    }


}

resources/views/app/pages/permissions/_form.blade.php
<form id="form" class="form-horizontal form-label-left" >
    @csrf
    @isset($permission)
        {{ method_field('PUT') }}
    @endisset
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Permission Name <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" id="name" required="required"  name="name" value="{{$permission->name ?? ''}}" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
</form>

resources/views/app/pages/permissions/_scripts.blade.php
<script>
    var btn;
    var modal;
    var form;
    $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#permissions-datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,

            ajax:{
                "url": '{!! route("permissions.datatable") !!}',
                "type": "GET",
            },
            columns: [
                { data: 'name', name: 'name' },
                { data: 'created_at', name: 'created_at'},
                { data: 'action', name: 'action',searchable:false,orderable:false},

            ],
            columnDefs:[
                {targets:2,"width":"10%"}
            ],
            "order": [[ 0, "asc" ]], //or asc
        });

    });

    /*render create-edit modal*/
    $('#modal-lg').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var button = $(event.relatedTarget); // Button that triggered the modal
        btn = button.data('btn'); // Extract info from data-* attributes
        modal = $(this);
        form = modal.find(".modal-body #form");
        form.trigger('reset');
        if (btn === 'create') {
            var url = '{{ route("permissions.create")}}';
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    modal.find('.modal-title').html('CREATE PERMISSION');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    form.attr('action', '{{ route("permissions.store")}}');
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Save');
                }
            })//end ajax
        } else if (btn === 'edit') {
            var permission_id = button.data('id');
            var url = '{{ route("permissions.edit",":permission_id")}}';
            url = url.replace(':permission_id', permission_id);
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    var url = '{{ route("permissions.update",":permission_id")}}';
                    url = url.replace(':permission_id', permission_id);
                    modal.find('.modal-title').html('EDIT PERMISSION');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    form.attr('action', url);
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Update');
                }
            })//end ajax
        }
    });

    $('#modal-lg-delete').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var button = $(event.relatedTarget); // Button that triggered the modal
        var permission_id = button.data('id');// Extract info from data-* attributes
        var url = '{{ route("permissions.destroy", ":permission_id") }}';
        url = url.replace(':permission_id', permission_id);
        modal = $(this);
        form = modal.find('.modal-body #form-delete');
        console.log(form);
        form.attr('action', url);
        console.log(form.attr('action', url));
        modal.find('.modal-title').html('DELETE PERMISSION');
        modal.find('.modal-body #message').html(' <strong>Permission will be DELETED!</strong> Are you sure to process this transaction?');
    });
    /*AJAX SUBMIT*/
    $(".btn-modal-submit").click(function (e) {
        e.preventDefault(); // avoid to execute the actual submit of the form.
        var url =  form.attr('action');
        console.log(url);
        $.ajax({
            type: form.attr('method'),
            url: url,
            data: form.serialize(), // serializes the form's elements.
            success: function (data) {
                checkValidation(form,data);
                $('#permissions-datatable').DataTable().ajax.reload();
                if(btn !== 'delete'){
                    modal.find('.modal-body #name').val(data.name)
                }
            }, error: function (xhr, ajaxOptions, thrownError) {
                checkValidation(form,xhr)
            }
        });
    });

    /*functions*/

    function checkValidation(form,data){
        if(data.status==='success'){
            var success = modal.find('.success-modal');
            success.fadeIn();
            success.html(data.message);
            success.css('display','');
            form.trigger("reset");
            success.delay(800).fadeOut(300, function(){
                success.css('display','none');
            });
        }else{
            var error = modal.find('.error-modal');
            var message = '';
            $.each(data.responseJSON.errors, function (key, value) {
                message += value
            });
            console.log(message);
            error.fadeIn();
            error.html(message);
            error.css('display','');
            error.delay(800).fadeOut(300, function(){
                error.css('display','none');
            })
        }
    }
</script>

resources/views/app/pages/permissions/index.blade.php
@extends("app.layout.app")
@section("title","Users")
@push("page-styles")
    <!-- bootstrap-progressbar -->
    <link href="{{asset("theme/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css")}}" rel="stylesheet">

    <!-- Datatables -->
    <link href="{{asset('theme')}}/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
@endpush

@section("content")
    <div style="margin-top: 50px;">
        <div class="page-title">
            <div class="title_left">
                <h3>Permissions</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <button type="button" class="btn btn-success" data-btn="create" data-toggle="modal" data-target="#modal-lg"><i class="fa fa-plus"></i> Create Permission</button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">
                            <table id="permissions-datatable" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push("page-scripts")
    <!-- Datatables -->


    <script src="{{asset('theme')}}/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="{{asset('theme')}}/vendors/jszip/dist/jszip.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="{{asset('theme')}}/vendors/validator/validator.js"></script>
    <script src="{{asset('theme')}}/vendors/moment/moment.js"></script>
@endpush

@push("scripts")
    @include('app.pages.permissions._scripts')
@endpush