routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//
Auth::routes();
//Auth::loginUsingId(1);
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', function(){
        return redirect('home');
    })->name('home');
    /*permissions*/
    Route::resource('permissions', 'PermissionController');
    Route::get('permissions-datatable', 'PermissionController@permissionDatatable')->name('permissions.datatable');

    /*roles*/
    Route::resource('roles', 'RoleController');
    Route::get('roles-datatable', 'RoleController@roleDatatable')->name('roles.datatable');

    /*users*/
    Route::resource('users', 'UserController');
    Route::DELETE('users-enabled/{user}', 'UserController@userEnabled')->name('users.enabled');
    Route::get('users-datatable', 'UserController@usersDatatable')->name('users.datatable');
//    Route::get('users-profile/{user}', 'UserController@usersDatatable')->name('users.profile');
});

resources/views/app/layout/side-bar/_menu-footer.blade.php
<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>

<!-- /menu footer buttons -->

resources/views/app/layout/side-bar/_menu-profile-quick-info.blade.php
<div class="profile clearfix">
    <div class="profile_pic">
        <img src="{{asset('theme')}}/images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
        <span>Welcome,</span>
        <h2>{{auth()->user()->name}}</h2>
    </div>
</div>

resources/views/app/layout/side-bar/_sidebar-menu.blade.php
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>Dashboard</h3>
        <ul class="nav side-menu">
            <li class="{{ Request::segment(1) == 'home'  ? 'active' : ''}} {{Request::segment(1) == ''  ? 'active' : '' }}"><a href="{{route('home')}}"><i class="fa fa-home"></i> Home</a></li>
        </ul>
    </div>
    <div class="menu_section">
        <h3>Administrator</h3>
        <ul class="nav side-menu">
            <li><a><i class="fa fa-users"></i> User Management <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li class="{{ Request::segment(1) == 'permissions'  ? 'active' : ''}}"><a href="{{route('permissions.index')}}">Permissions</a></li>
                    <li class="{{ Request::segment(1) == 'roles'  ? 'active' : ''}}"><a href="{{route('roles.index')}}">Roles</a></li>
                    <li class="{{Request::segment(1) == 'users'  ? 'active' : ''}}"><a href="{{route('users.index')}}">Users</a></li>
                </ul>
            </li>
      </ul>
    </div>
</div>

resources/views/app/layout/side-bar/side-bar.blade.php
<div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
    </div>
    <div class="clearfix"></div>
    <!-- menu profile quick info -->
@include('app.layout.side-bar._menu-profile-quick-info')
<!-- /menu profile quick info -->
    <br />
    <!-- sidebar menu -->
@include('app.layout.side-bar._sidebar-menu')
<!-- /sidebar menu -->
    <!-- /menu footer buttons -->
@include('app.layout.side-bar._menu-footer')
<!-- /menu footer buttons -->
</div>