routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//
Auth::routes();
//Auth::loginUsingId(1);
Route::group(['middleware' => 'auth'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/', function(){
        return redirect('home');
    })->name('home');
    /*permissions*/
    Route::resource('permissions', 'PermissionController');
    Route::get('permissions-datatable', 'PermissionController@permissionDatatable')->name('permissions.datatable');

    /*roles*/
    Route::resource('roles', 'RoleController');
    Route::get('roles-datatable', 'RoleController@roleDatatable')->name('roles.datatable');

    /*users*/
    Route::resource('users', 'UserController');
    Route::DELETE('users-enabled/{user}', 'UserController@userEnabled')->name('users.enabled');
    Route::get('users-datatable', 'UserController@usersDatatable')->name('users.datatable');
//    Route::get('users-profile/{user}', 'UserController@usersDatatable')->name('users.profile');
});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;
use Yajra\DataTables\Facades\DataTables;

class User extends Authenticatable
{
    use  HasRoles,Notifiable,SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id', 'created_at','updated_at'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'created_at' => 'datetime:M d, Y h:i:s a',
    ];

    public function setPasswordAttribute($input)
    {
        if ($input)
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
    }

    public function role()
    {
        return $this->belongsToMany(Role::class, 'role_user');
    }

    public function scopeHasRoles(\Illuminate\Database\Eloquent\Builder $query, $roles)
    {
        return $this->scopeRole($query, $roles);
    }

    public static function usersDatatable(){

        $data = User::query()->withTrashed()->with('roles')
            ->select('users.*');
        return DataTables::eloquent($data)
            ->addColumn('action', function ($data) {
                    $html='';
                if($data->deleted_at ==  null){
                    $html='<a href="'.route('users.show',$data->id).'" type="button">
                        <span class="label label-success">View</span>
                        </a>';
                    $html.='<a href="" type="button" data-btn="edit" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg">
                        <span class="label label-info">Edit</span>
                        </a>';
                    $html.='<a href="" type="button" data-btn="delete" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg-delete">
                        <span class="label label-warning">Disable</span>
                        </a>';
                }else{
                    $html.='<a href="" type="button" data-btn="enable" data-id="'.$data->id.'" data-toggle="modal" data-target="#modal-lg-delete">
                        <span class="label label-default">Enable</span>
                        </a>';
                }

                return  $html;
            })
            ->addColumn('roles', function ($data) {
                $html = '';
                if(isset($data->roles)){
                    foreach($data->roles()->pluck('name') as $role){
                        $html.= ' <span class="badge badge-primary">'.$role.'</span>';
                    }
                }
                return  $html;
            })
            ->filterColumn('roles', function ($query, $keyword) {
                $query ->selectraw("select name from roles where name = ?", ["%$keyword%"]);
            })
            ->rawColumns(['roles','action'])
            ->make(true);
    }

    public static function userStore($request){

        //create user
        $user = User::create($request->except('roles','password_confirmation'));
        //assigning roles to user
        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->assignRole($roles);

        if($user){
            return  response()->json([
                'status'=>'success',
                'message'=>'User successfully created'
            ]);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('user_view')) {
            return abort(403);
        }
        return view('app.pages.users.index');
    }

    public function usersDatatable(){
        if (! Gate::allows('user_view')) {
            return abort(403);
        }
        $data = User::usersDatatable();
        return $data;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()

    {
        if (! Gate::allows('user_create')) {
            return abort(403);
        }
        $roles = Role::all();
        //render form
        $form = view()->make('app.pages.users._form',compact('roles'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        if (! Gate::allows('user_create')) {
            return abort(403);
        }
        $user = User::userStore($request);
        return $user;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('user_view')) {
            return abort(403);
        }
        $user = User::findorfail($id);
        return view('app.pages.users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('user_update')) {
            return abort(403);
        }
        $user = User::find($id);
        $roles = Role::all();
        $form = view()->make('app.pages.users._form',compact('user','roles'))->render();
        //save to variable
        $data = array(
            'form' => $form,
        );
        //return json
        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        if (! Gate::allows('user_update')) {
            return abort(403);
        }
        $user = User::findOrFail($id);
        $user->update($request->except('roles','password_confirmation'));
        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->syncRoles($roles);
        if($user){
            return  response()->json([
                'status'=>'success',
                'message'=>'User Successfully Updated'
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    { //find user
        if (! Gate::allows('user_disable')) {
            return abort(403);
        }
        $user = User::findOrFail($id);
        //delete user
        $user->delete();

        if($user){
            return  response()->json([
                'status'=>'success',
                'message'=>'User Successfully disabled',
            ]);
        }
    }

    public function userEnabled($id)
    { //find user
        if (! Gate::allows('user_enable')) {
            return abort(403);
        }
        $user = User::withTrashed()->find($id)->restore();
        if($user){
            return  response()->json([
                'status'=>'success',
                'message'=>'User Successfully enabled',
            ]);
        }
    }
}

resources/views/app/pages/users/_form.blade.php
<form id="form" class="form-horizontal form-label-left">
    @csrf
    @isset($user)
        {{ method_field('PUT') }}
    @endisset
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Full Name <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="name" required="required" value="{{$user->name ?? ''}}" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="username">Username <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="username" required="required" value="{{$user->username ?? ''}}" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="email" required="required" value="{{$user->email ?? ''}}" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">Password <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="password" name="password" required="required" value="" class="form-control col-md-7 col-xs-12">
            @isset($user)
            <small class="text-navy">Leave blank if you don't want to change password</small>
            @endif
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="password_confirmation">Confirm Password <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="password" name="password_confirmation" required="required" value="" class="form-control col-md-7 col-xs-12">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-3 col-sm-3 col-xs-12 control-label">Select Role <span class="required">*</span>
            <br>
            <small class="text-navy">User can have 1 or more roles</small>
        </label>
        <div class="col-md-9 col-sm-9 col-xs-12">
            @forelse($roles as $key=>$role)
                <div class="checkbox">
                    <label>
                        @if(isset($user))
                            <input type="checkbox" class="flat" name="roles[]" value="{{$role->name}}"
                                   @foreach($user->roles()->pluck('name') as $user_role)
                                   @if($user_role== $role->name)
                                   checked="checked"
                                @endif
                                @endforeach
                            > {{$role->name}}
                        @else
                            <input type="checkbox" class="flat" name="roles[]" value="{{$role->name}}" > {{$role->name}}
                        @endif
                    </label>
                </div>
            @empty
                <div class="checkbox">
                    <label>
                        No Roles
                    </label>
                </div>
            @endforelse
        </div>
    </div>
</form>

resources/views/app/pages/users/_scripts.blade.php
<script>
    var btn;
    var modal;
    var form;
    var table;
    $(document).ready(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

       table = $('#users-datatable').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,

            ajax:{
                "url": '{!! route("users.datatable") !!}',
                "type": "GET",
            },
            columns: [
                { data: 'name', name: 'name' },
                { data: 'username', name: 'username' },
                { data: 'email', name: 'email'},
                { data: 'roles', name: 'roles'},
                { data: 'created_at', name: 'created_at'},
                { data: 'action', name: 'action',searchable:false,orderable:false},

            ],
           columnDefs:[
               {targets:5,"width":"13%"}
           ],
           "createdRow": function( row, data, dataIndex){

               if( data['deleted_at'] != null){
                   $(row).addClass('alert-danger');
               }
           },
            "order": [[ 0, "asc" ]], //or asc
        });

    });

    /*render create-edit modal*/
    $('#modal-lg').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var button = $(event.relatedTarget); // Button that triggered the modal
        btn = button.data('btn'); // Extract info from data-* attributes
        modal = $(this);
        modal.find('.btn-modal-submit').css('display','');
        form = modal.find(".modal-body #form");
        form.trigger('reset');
        if (btn === 'create') {
            var url = '{{ route("users.create")}}';
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    modal.find('.modal-title').html('CREATE USER');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    $('input.flat').iCheck({
                        checkboxClass: 'icheckbox_flat-green',
                        radioClass: 'iradio_flat-green'
                    });
                    form.attr('action', '{{ route("users.store")}}');
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Save');
                }
            })//end ajax
        } else if (btn === 'edit') {
            var user_id = button.data('id');
            var url = '{{ route("users.edit",":user_id")}}';
            url = url.replace(':user_id', user_id);
            $.ajax({
                url: url, //this is your uri
                type: 'get', //this is your method
                dataType: 'json',
                success: function (response) {
                    //console.log(response.form);
                    var url = '{{ route("users.update",":user_id")}}';
                    url = url.replace(':user_id', user_id);
                    modal.find('.modal-title').html('EDIT USER');
                    modal.find('.modal-body').html(response.form);
                    form = modal.find(".modal-body #form");
                    form.find('input.flat').iCheck({
                        checkboxClass: 'icheckbox_flat-green',
                        radioClass: 'iradio_flat-green'
                    });
                    form.attr('action', url);
                    form.attr('method', 'POST');
                    modal.find('.btn-modal-submit').html('Update');
                }
            })//end ajax
        }
    });

    $('#modal-lg-delete').on('show.bs.modal', function (event) {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        var button = $(event.relatedTarget); // Button that triggered the modal
        var user_id = button.data('id');// Extract info from data-* attributes

        modal = $(this);
        modal.find('.btn-modal-submit').css('display','');
        btn = button.data('btn');
        if(btn==='delete'){
            var url = '{{ route("users.destroy", ":user_id") }}';
            url = url.replace(':user_id', user_id);
            form = modal.find('.modal-body #form-delete');
            form.attr('action', url);
            modal.find('.modal-title').html('DISABLED USER');
            modal.find('.modal-body #message').html(' <strong>User will be DISABLED!</strong> Are you sure to process this transaction?');
            modal.find('.btn-modal-submit').html('Disabled');
        }else if(btn==='enable'){
            var url = '{{ route("users.enabled", ":user_id") }}';
            url = url.replace(':user_id', user_id);
            form = modal.find('.modal-body #form-delete');
            form.attr('action', url);
            modal.find('.modal-title').html('ENABLED USER');
            modal.find('.modal-body #message').html(' <strong>User will be ENABLED!</strong> Are you sure to process this transaction?');
            modal.find('.btn-modal-submit').html('Enable');
        }

    });

    /*AJAX SUBMIT*/
    $(".btn-modal-submit").click(function (e) {
        e.preventDefault(); // avoid to execute the actual submit of the form.
        var url =  form.attr('action');
        console.log(url);
        $.ajax({
            type: form.attr('method'),
            url: url,
            data: form.serialize(), // serializes the form's elements.
            success: function (data) {
                checkValidation(form,data);
                $('#users-datatable').DataTable().ajax.reload();
                if(btn !== 'delete' || btn !=='enable'){
                    modal.find('.modal-body #name').val(data.name)
                }
            }, error: function (xhr, ajaxOptions, thrownError) {
                checkValidation(form,xhr)
            }
        });
    });

    /*functions*/

    function checkValidation(form,data){
        if(data.status==='success'){
            var success = modal.find('.success-modal');
            success.fadeIn();
            success.html(data.message);
            success.css('display','');
            form.trigger("reset");
            if(btn==='create'){
                form.find('input.flat').iCheck('update');
            }

            if(btn==='delete' || btn ==='enable'){
                modal.find('.btn-modal-submit').css('display','none');
            }
            success.delay(1000).fadeOut(300, function(){
                success.css('display','none');
                if(btn==='delete' || btn ==='enable'){
                    modal.modal('hide');
                }
            });
        }else{
            var error = modal.find('.error-modal');
            var message = '';
            var count = 0;
            $.each(data.responseJSON.errors, function (key, value) {
                count++;
                if(count>1){
                    message+='<br>';
                }
                message += value
            });
            console.log(message);
            error.fadeIn();
            error.html(message);
            error.css('display','');
            error.delay(1000).fadeOut(300, function(){
                error.css('display','none');
            })
        }
    }

</script>

resources/views/app/pages/users/index.blade.php
@extends("app.layout.app")
@section("title","Users")
@push("page-styles")
    <!-- bootstrap-progressbar -->
    <link href="{{asset("theme/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css")}}" rel="stylesheet">

    <!-- Datatables -->
    <link href="{{asset('theme')}}/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
@endpush

@section("content")
    <div style="margin-top: 50px;">
        <div class="page-title">
            <div class="title_left">
                <h3>Users</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <button type="button" class="btn btn-success" data-btn="create" data-toggle="modal" data-target="#modal-lg"><i class="fa fa-plus"></i> Create User</button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">
                            <table id="users-datatable" class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>Roles</th>
                                    <th>Date Created</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push("page-scripts")
    <!-- iCheck -->
    <script src="{{asset('theme')}}/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="{{asset('theme')}}/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="{{asset('theme')}}/vendors/jszip/dist/jszip.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="{{asset('theme')}}/vendors/validator/validator.js"></script>
    <script src="{{asset('theme')}}/vendors/moment/moment.js"></script>
@endpush

@push("scripts")
    @include('app.pages.users._scripts')
@endpush

resources/views/app/pages/users/user-profile.blade.php
@extends("app.layout.app")
@section("title","User-Profile")
@push("page-styles")
    <!-- bootstrap-progressbar -->
    <link href="{{asset("theme/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css")}}" rel="stylesheet">

    <!-- Datatables -->
    <link href="{{asset('theme')}}/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="{{asset('theme')}}/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
@endpush

@section("content")
    <div style="margin-top: 50px;">
        <div class="page-title">
            <div class="title_left">
                <h3>User Profile</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <button type="button" class="btn btn-success" data-btn="create" data-toggle="modal" data-target="#modal-lg"><i class="fa fa-plus"></i> Create User</button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push("page-scripts")
    <!-- iCheck -->
    <script src="{{asset('theme')}}/vendors/iCheck/icheck.min.js"></script>
    <!-- Datatables -->
    <script src="{{asset('theme')}}/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="{{asset('theme')}}/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="{{asset('theme')}}/vendors/jszip/dist/jszip.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="{{asset('theme')}}/vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="{{asset('theme')}}/vendors/validator/validator.js"></script>
    <script src="{{asset('theme')}}/vendors/moment/moment.js"></script>
@endpush

@push("scripts")
    @include('app.pages.users._scripts')
@endpush